***Name: Mansi Gharat BE COMPS
Div: A Roll No.37 DL EXP8***

In [ ]:
apsit = """A P Shah Institute of Technology Thane.
A. P. Shah Institute of Technology (APSIT) has started functioning with commitment of imparting state of art technical education so as to inculcate conceptual know-how, analyzing skills, decision making abilities and leadership qualities in the students.
APSIT stands committed to the intellectual and moral growth of every student.
APSIT has experienced and proficient team which aspires to unlock the hidden potential in subconscious minds of students and to create competent Engineers with vision & social commitment.
Parshvanath Charitable Trust
A. P. Shah Institute of Technology is managed by Parshvanath Charitable Trust (PCT) which was established in November, 1993, under the leadership of Late Shri Ashokbhai Shah.
PCT is committed, to provide all the world class facilities, infrastructure, technology and the appropriate environment to the students to achieve their goals of becoming successful professionals in the present era of globalization.
The trust aspires to develop APSIT which will be recognized all over the globe as one of the prominent and authentic centres of technological training & research.
BOARD OF TRUSTEES:
SHRI. CHIRAG A. SHAH,     CHAIRMAN
SHRI. NIRANJAN P. SHAH,     SECRETARY
SMT. POOJA C. SHAH,     TRUSTEE
SHRI. KUNTHAL N. SHAH,     TRUSTEE
SHRI. MINESH N. SHAH,     TRUSTEE
SHRI. HITANSHU C. SHAH,     TRUSTEE
A. P. Shah Institute Of Technology is  governed by  Parshavnath Charitable Trust which was founded by my father Hon'ble Shree Ashokbhai P Shah in 1993.
To run an engineering college in the trust my father had a dream that a person who comes to Mumbai, he can study in a good institute with a very low fees.
It is my privilege to welcome you to the website of our Institute, dedicated to the quality technical education with all round development of the students to be competent professional Engineers of tomorrows to serve the society.
We have exemplary infrastructural facilities, well equipped laboratories, separate computer center, the team of highly qualified faculty and the exhilarating atmosphere in the campus will surely take you to enviable heights in your capabilities and achievements.
We have research oriented, challenge seeking, well qualified and devoted faculty to train the students in quality technical education. The ultimate aim of our management and staff is to get higher percentage to our students and place them in multi-national companies.
We conduct Seminars, Workshops, STTP, National and International conferences to update the development in science technology.
Principal message I believe that the institute will continue to produce competent technocrats and managers who will make significant contribution to the corporate world and industries all over the world which will enable them to serve as global citizens.
DEPARTMENTS:
Computer Engineering
Civil Engineering
Information Technology
Mechanical Engineering
CSE AI and ML
CSE Data Science
About Training and Placement
Training and Placement department is dedicated towards proper placement of students .It advices students on career options and provides the latest information on training & employment opportunities.
Focus areas are providing guidance, counseling and bringing students and potential employers together to achive the best possible placement depending on the market conditions .The department looks after the interest of the students and the employers by providing them the necessary platform.
Objective
To organize campus recruitment for final year students in reputed companies.
To facilitate companies for recruiting candidates as per their requirements.
Creating awareness amongst the students regarding various career options.
To enhance students employability by providing training in Aptitude & soft skills.
Helping students for summer training/internship programme.
Bridging gap between Industry and Academia through:
Seminars, Guest Lectures, Conferences, Corporate Meets & Industrial Visits etc.
Coordinating with various departments for imparting value added industry skills.
About Training
The objective of the training department is to match the corporate expectations by providing them Soft skills, Aptitude & Technical training.
The effectiveness of these training is evident from the consistent placement results. Several companies have been visiting the college every year to tap and recruit the young talented students.
Guest lectures & Mock interview sessions are being organized with the help of industry experts to bridge the gap between industry & academia.
A separate training department focuses on the all-round growth of students by offering certifications such as MTA, PTC, Cloud computing, Java, .net, Big Data, Robotics, Design and simulation keeping each student's core subject and year in mind.
Training & Placement Polices
The role of the Training and Placement Cell is of a facilitator and councillor for placement related activities. Training and Placement cell does not guarantee a job.
Students to consult their Training & Placement Department before registration for the Industry in case of queries.
The information about the placement opportunities, schedules etc. will be displayed on T&P Notice Board, near Reception. Students must read this board daily. WhatsApp messages also will be given. After that, no responsibility of  providing info lies with T&P Dept.
It is Mandatory for the students interested in Campus Placement to attend various Training programs/ sessions arranged at Institute level.
Attending interview without basic preparation (profile/company info etc.) will lead to debarment for few months
Once registered, students CAN NOT back out from the further interview processes.
Non Attendance for the interview process without prior permission of T&P office, will lead to disqualification from Campus Placement Activities permanently.
Once shortlisted, it is mandatory for the students to go through the subsequent selection processes. Attending process casually, underperforming is a disqualification for further opportunities.
Institute formals during campus process is Mandatory.
About Training & Placement Cell.
The Training and Placement cell plays a crucial role in reducing the gap between the Campus and Corporate. It is the dream of every engineering student to get placed in a top organization visiting their campus for recruitment.
The Cell operates round the year to facilitate contacts between Hiring Companies and Graduates.
The objective of APSIT, Training & Placement Cell is to place all eligible students in reputed IT and core manufacturing, infrastructure companies right at the campus itself.
To achieve this objective the cell liaises with the various industrial establishments, corporate houses which conduct campus interviews and select students from all disciplines, by identifying their knowledge skills, attitude matrices of every individual student, creating job profiles for them, identifying areas of training & various methods as per the training requirement.
The challenge today is to make students more competent, and ‘Industry Ready’.
Companies Requirement
Excellent Aptitude
Technical Expert
Soft Skills
Positive Approach
Thus, College Aim at
Bridging the Gap between Industry and Academics
Enhancing Employability
Developing All-round Personality
Inculcating Managerial Skills.
Training and Placement Cell Activities:
Arranging in-plant training and industrial visits, during every academic year.
Facilitate Student Internships, during every academic year
Organizing guest lectures by inviting Corporate Professionals & distinguished Educationists/Academicians.
Imparting personality development programs to enhance the soft skills & Communications skills of the Students.
To motivate aspiring students to prepare for higher studies and guiding them to take exams such as CAT, GATE, TOEFL, GRE, IES, UPSC, TNPSC etc.
Conducting Mock & Preparatory Tests to take up competitive examinations for Higher Studies or for Employment
Ensuring training for students during vacations, by proven & reputed firms both on General Aptitude and Technical Aptitude
Arranging ON / OFF campus interviews.
Communication, Aptitude and Personality Training is imparted to the Students from 2nd year onwards and will be an on-going affair till the odd-semester of their final year.
Training Module consists of the following
Technical Aptitude
Communication Skills
General Aptitude
Quantitative Reasoning
Logical Reasoning
Verbal Reasoning
Group Discussion
Interview Skills
Address: Survey No. 12, Opp. Hypercity Mall, Kasarvadavali, Ghodbunder Road, Thane West, Thane, Maharashtra, India 400615
Email: reception@apsit.edu.in
Public Transporations: APSIT is well connected by number of buses of BEST, TMT, NMMT, MSRTC, MBMT and VVMT. You may get down at Kasarvadavali bus stop to reach APSIT.
From Thane:
ST Bus Depot Near Thane West Station: Thane - Borivali, Thane - Bhayander, Thane-Ovala
TMT Bus Stand Near Thane West Station: Thane - Kasarvadavali, Thane - Ovala, Thane - Miraroad """

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([apsit]) # assign numbers as index to words

In [ ]:
tokenizer.word_index

{'the': 1,
 'to': 2,
 'and': 3,
 'of': 4,
 'students': 5,
 'training': 6,
 'in': 7,
 'is': 8,
 'placement': 9,
 'for': 10,
 'a': 11,
 'shah': 12,
 'thane': 13,
 'skills': 14,
 'by': 15,
 'will': 16,
 'campus': 17,
 'p': 18,
 'institute': 19,
 'apsit': 20,
 'with': 21,
 'all': 22,
 'on': 23,
 'year': 24,
 'aptitude': 25,
 'cell': 26,
 'technology': 27,
 'technical': 28,
 'as': 29,
 'companies': 30,
 'every': 31,
 'which': 32,
 'shri': 33,
 'their': 34,
 'it': 35,
 'them': 36,
 'corporate': 37,
 'industry': 38,
 'from': 39,
 'trust': 40,
 'be': 41,
 'engineering': 42,
 'department': 43,
 'providing': 44,
 'various': 45,
 'between': 46,
 'interview': 47,
 'student': 48,
 'competent': 49,
 'trustee': 50,
 'round': 51,
 'about': 52,
 'objective': 53,
 'soft': 54,
 'gap': 55,
 'etc': 56,
 'at': 57,
 'during': 58,
 'imparting': 59,
 'education': 60,
 'charitable': 61,
 'world': 62,
 'board': 63,
 'my': 64,
 'college': 65,
 'that': 66,
 'you': 67,
 'our': 68,
 'development': 69,
 'we': 70,
 'h

In [ ]:
len(tokenizer.word_index)

554

In [ ]:
for sentence in apsit.split('\n'):
  print(sentence)

A P Shah Institute of Technology Thane.
A. P. Shah Institute of Technology (APSIT) has started functioning with commitment of imparting state of art technical education so as to inculcate conceptual know-how, analyzing skills, decision making abilities and leadership qualities in the students. 
APSIT stands committed to the intellectual and moral growth of every student.
APSIT has experienced and proficient team which aspires to unlock the hidden potential in subconscious minds of students and to create competent Engineers with vision & social commitment.
Parshvanath Charitable Trust
A. P. Shah Institute of Technology is managed by Parshvanath Charitable Trust (PCT) which was established in November, 1993, under the leadership of Late Shri Ashokbhai Shah.
PCT is committed, to provide all the world class facilities, infrastructure, technology and the appropriate environment to the students to achieve their goals of becoming successful professionals in the present era of globalization.
T

In [ ]:
for sentence in apsit.split('\n'):
  print(tokenizer.texts_to_sequences([sentence])[0]) # convert a list of words into sequence based on vocabulary

[11, 18, 12, 19, 4, 27, 13]
[11, 18, 12, 19, 4, 27, 20, 93, 188, 189, 21, 94, 4, 59, 190, 4, 191, 28, 60, 192, 29, 2, 193, 194, 195, 196, 197, 14, 198, 199, 200, 3, 95, 201, 7, 1, 5]
[20, 202, 96, 2, 1, 203, 3, 204, 97, 4, 31, 48]
[20, 93, 205, 3, 206, 98, 32, 99, 2, 207, 1, 208, 100, 7, 209, 210, 4, 5, 3, 2, 211, 49, 101, 21, 212, 213, 94]
[102, 61, 40]
[11, 18, 12, 19, 4, 27, 8, 214, 15, 102, 61, 40, 103, 32, 104, 215, 7, 216, 105, 217, 1, 95, 4, 218, 33, 106, 12]
[103, 8, 96, 2, 219, 22, 1, 62, 220, 107, 108, 27, 3, 1, 221, 222, 2, 1, 5, 2, 109, 34, 223, 4, 224, 225, 110, 7, 1, 226, 227, 4, 228]
[1, 40, 99, 2, 229, 20, 32, 16, 41, 230, 22, 111, 1, 231, 29, 232, 4, 1, 233, 3, 234, 235, 4, 236, 6, 112]
[63, 4, 237]
[33, 238, 11, 12, 239]
[33, 240, 18, 12, 241]
[242, 243, 113, 12, 50]
[33, 244, 114, 12, 50]
[33, 245, 114, 12, 50]
[33, 246, 113, 12, 50]
[11, 18, 12, 19, 4, 27, 8, 247, 15, 248, 61, 40, 32, 104, 249, 15, 64, 115, 250, 251, 106, 18, 12, 7, 105]
[2, 252, 116, 42, 65, 7, 1, 

In [ ]:
input_sequences = []
for sentence in apsit.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [ ]:
input_sequences

[[11, 18],
 [11, 18, 12],
 [11, 18, 12, 19],
 [11, 18, 12, 19, 4],
 [11, 18, 12, 19, 4, 27],
 [11, 18, 12, 19, 4, 27, 13],
 [11, 18],
 [11, 18, 12],
 [11, 18, 12, 19],
 [11, 18, 12, 19, 4],
 [11, 18, 12, 19, 4, 27],
 [11, 18, 12, 19, 4, 27, 20],
 [11, 18, 12, 19, 4, 27, 20, 93],
 [11, 18, 12, 19, 4, 27, 20, 93, 188],
 [11, 18, 12, 19, 4, 27, 20, 93, 188, 189],
 [11, 18, 12, 19, 4, 27, 20, 93, 188, 189, 21],
 [11, 18, 12, 19, 4, 27, 20, 93, 188, 189, 21, 94],
 [11, 18, 12, 19, 4, 27, 20, 93, 188, 189, 21, 94, 4],
 [11, 18, 12, 19, 4, 27, 20, 93, 188, 189, 21, 94, 4, 59],
 [11, 18, 12, 19, 4, 27, 20, 93, 188, 189, 21, 94, 4, 59, 190],
 [11, 18, 12, 19, 4, 27, 20, 93, 188, 189, 21, 94, 4, 59, 190, 4],
 [11, 18, 12, 19, 4, 27, 20, 93, 188, 189, 21, 94, 4, 59, 190, 4, 191],
 [11, 18, 12, 19, 4, 27, 20, 93, 188, 189, 21, 94, 4, 59, 190, 4, 191, 28],
 [11, 18, 12, 19, 4, 27, 20, 93, 188, 189, 21, 94, 4, 59, 190, 4, 191, 28, 60],
 [11,
  18,
  12,
  19,
  4,
  27,
  20,
  93,
  188,
  189,
  2

In [ ]:
max([len(x) for x in input_sequences])

51

In [ ]:
max_len = max([len(x) for x in input_sequences])

In [ ]:
#zero padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [ ]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  11,  18],
       [  0,   0,   0, ...,  11,  18,  12],
       [  0,   0,   0, ...,  18,  12,  19],
       ...,
       [  0,   0,   0, ...,  90,  13, 187],
       [  0,   0,   0, ...,  13, 187,  13],
       [  0,   0,   0, ..., 187,  13, 554]], dtype=int32)

In [ ]:
padded_input_sequences[:,:-1]

array([[  0,   0,   0, ...,   0,   0,  11],
       [  0,   0,   0, ...,   0,  11,  18],
       [  0,   0,   0, ...,  11,  18,  12],
       ...,
       [  0,   0,   0, ...,  13,  90,  13],
       [  0,   0,   0, ...,  90,  13, 187],
       [  0,   0,   0, ...,  13, 187,  13]], dtype=int32)

In [ ]:
X = padded_input_sequences[:,:-1]

In [ ]:
padded_input_sequences[:,-1]

array([ 18,  12,  19, ..., 187,  13, 554], dtype=int32)

In [ ]:
y = padded_input_sequences[:,-1]

In [ ]:
X.shape

(1211, 50)

In [ ]:
y.shape

(1211,)

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=555)

In [ ]:
y.shape

(1211, 555)

In [ ]:
y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential()
model.add(Embedding(555, 100, input_length=50))
model.add(LSTM(150))
model.add(Dense(555, activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 100)           55500     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 555)               83805     
                                                                 
Total params: 289905 (1.11 MB)
Trainable params: 289905 (1.11 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
38/38 [==============================] - 6s 92ms/step - loss: 6.0698 - accuracy: 0.0462
Epoch 2/100
38/38 [==============================] - 3s 91ms/step - loss: 5.7098 - accuracy: 0.0520
Epoch 3/100
38/38 [==============================] - 6s 163ms/step - loss: 5.6397 - accuracy: 0.0520
Epoch 4/100
38/38 [==============================] - 3s 89ms/step - loss: 5.6068 - accuracy: 0.0520
Epoch 5/100
38/38 [==============================] - 3s 90ms/step - loss: 5.5557 - accuracy: 0.0570
Epoch 6/100
38/38 [==============================] - 5s 121ms/step - loss: 5.4688 - accuracy: 0.0553
Epoch 7/100
38/38 [==============================] - 4s 90ms/step - loss: 5.3396 - accuracy: 0.0685
Epoch 8/100
38/38 [==============================] - 3s 90ms/step - loss: 5.1838 - accuracy: 0.0941
Epoch 9/100
38/38 [==============================] - 4s 93ms/step - loss: 5.0011 - accuracy: 0.0925
Epoch 10/100
38/38 [==============================] - 5s 119ms/step - loss: 4.7972 - accuracy: 0.1

In [ ]:
text = "shah"
#tokenize
tokenizer.texts_to_sequences([text])[0] #gives list not nested list

[12]

In [ ]:
token_text = tokenizer.texts_to_sequences([text])[0]

In [ ]:
#padding
pad_sequences([token_text], maxlen=50, padding='pre')


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0, 12]], dtype=int32)

In [ ]:
padded_token_text = pad_sequences([token_text], maxlen=50, padding='pre')

In [ ]:
#predict probabilities for 555 multiclasses
model.predict(padded_token_text)

1/1 [==============================] - 0s 478ms/step


array([[1.92544030e-06, 4.56139642e-05, 1.06843922e-03, 3.92149249e-03,
        2.02255696e-03, 2.78069498e-03, 2.26729065e-01, 2.58456194e-03,
        9.40985454e-04, 3.60795204e-03, 2.04059551e-03, 6.01973406e-05,
        2.81602152e-05, 6.08640630e-03, 7.49253761e-03, 1.59982839e-04,
        3.33513017e-04, 3.57439771e-04, 7.20098615e-03, 1.83261652e-02,
        2.12028064e-03, 2.90976110e-04, 4.22216777e-04, 1.23922736e-03,
        1.37613824e-04, 5.76636940e-03, 9.68525535e-04, 8.82905349e-02,
        1.25142850e-03, 1.96347719e-05, 2.86994618e-04, 3.97871016e-04,
        1.74440705e-04, 9.95920072e-06, 9.83283280e-06, 8.64357396e-04,
        3.46789898e-06, 9.02984248e-05, 3.57084238e-04, 6.74346347e-06,
        9.96379385e-05, 2.48182403e-07, 1.07852370e-01, 8.33592750e-03,
        1.25328341e-04, 4.40357439e-03, 1.82489178e-03, 3.49508664e-05,
        5.34711231e-04, 2.97887880e-07, 7.62858568e-03, 1.15024636e-03,
        2.28205901e-02, 7.53134675e-03, 4.44745971e-03, 3.683369

In [ ]:
#555 multiclasses
model.predict(padded_token_text).shape

1/1 [==============================] - 0s 30ms/step


(1, 555)

In [ ]:
import numpy as np

In [ ]:
np.argmax(model.predict(padded_token_text))

1/1 [==============================] - 0s 49ms/step


6

In [ ]:
tokenizer.word_index

{'the': 1,
 'to': 2,
 'and': 3,
 'of': 4,
 'students': 5,
 'training': 6,
 'in': 7,
 'is': 8,
 'placement': 9,
 'for': 10,
 'a': 11,
 'shah': 12,
 'thane': 13,
 'skills': 14,
 'by': 15,
 'will': 16,
 'campus': 17,
 'p': 18,
 'institute': 19,
 'apsit': 20,
 'with': 21,
 'all': 22,
 'on': 23,
 'year': 24,
 'aptitude': 25,
 'cell': 26,
 'technology': 27,
 'technical': 28,
 'as': 29,
 'companies': 30,
 'every': 31,
 'which': 32,
 'shri': 33,
 'their': 34,
 'it': 35,
 'them': 36,
 'corporate': 37,
 'industry': 38,
 'from': 39,
 'trust': 40,
 'be': 41,
 'engineering': 42,
 'department': 43,
 'providing': 44,
 'various': 45,
 'between': 46,
 'interview': 47,
 'student': 48,
 'competent': 49,
 'trustee': 50,
 'round': 51,
 'about': 52,
 'objective': 53,
 'soft': 54,
 'gap': 55,
 'etc': 56,
 'at': 57,
 'during': 58,
 'imparting': 59,
 'education': 60,
 'charitable': 61,
 'world': 62,
 'board': 63,
 'my': 64,
 'college': 65,
 'that': 66,
 'you': 67,
 'our': 68,
 'development': 69,
 'we': 70,
 'h

In [ ]:
pos = np.argmax(model.predict(padded_token_text))
for word,index in tokenizer.word_index.items():
    if index == pos:
      print(word)

1/1 [==============================] - 0s 29ms/step
training


In [ ]:
# predict next 10 words
import time
text = "A P Shah"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=50, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 [==============================] - 0s 31ms/step
A P Shah institute
1/1 [==============================] - 0s 30ms/step
A P Shah institute of
1/1 [==============================] - 0s 46ms/step
A P Shah institute of technology
1/1 [==============================] - 0s 29ms/step
A P Shah institute of technology is
1/1 [==============================] - 0s 31ms/step
A P Shah institute of technology is managed
1/1 [==============================] - 0s 30ms/step
A P Shah institute of technology is managed by
1/1 [==============================] - 0s 30ms/step
A P Shah institute of technology is managed by parshvanath
1/1 [==============================] - 0s 32ms/step
A P Shah institute of technology is managed by parshvanath charitable
1/1 [==============================] - 0s 37ms/step
A P Shah institute of technology is managed by parshvanath charitable trust
1/1 [==============================] - 0s 32ms/step
A P Shah institute of technology is managed by parshvanath charitable trus

In [ ]:
# predictiction on unseen data
import time
text = "exam"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=50, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 [==============================] - 0s 29ms/step
exam aptitude
1/1 [==============================] - 0s 31ms/step
exam aptitude and
1/1 [==============================] - 0s 34ms/step
exam aptitude and personality
1/1 [==============================] - 0s 28ms/step
exam aptitude and personality training
1/1 [==============================] - 0s 30ms/step
exam aptitude and personality training is
1/1 [==============================] - 0s 32ms/step
exam aptitude and personality training is imparted
1/1 [==============================] - 0s 54ms/step
exam aptitude and personality training is imparted to
1/1 [==============================] - 0s 31ms/step
exam aptitude and personality training is imparted to the
1/1 [==============================] - 0s 31ms/step
exam aptitude and personality training is imparted to the students
1/1 [==============================] - 0s 32ms/step
exam aptitude and personality training is imparted to the students from
